### ISSUE TITLE
Inverser les touches j et k

### ISSUE THREAD

**Issue by pyg77** [framasoft/ttrss#1]
Remarque de Kazé sur Twitter :  https://twitter.com/fabi1cazenave/status/345551491131654144

"pour moi comme pour tous les vimistes, TinyTinyRSS est inutilisable : les touches J et K sont inversées. Sinon j’aurais bien essayé…"

Si le comportement est effectivement contre-productif, on peut peut être patcher ça ?
A voir...

[complément: ça pourrait se faire par un micro-plugin : https://github.com/framasoft/Tiny-Tiny-RSS/blob/master/plugins/swap_jk/init.php ]

**Comment by fabi1cazenave** [comment]
Pour info, le lead dev du projet est au courant mais a refusé les correctifs « pour ne pas casser les habitudes existantes ». Il faudrait donc soit faire une modification locale (ce qui rendrait chaque mise à jour tellement plus amusante !), soit passer par une extension quelconque (aucune idée de comment ça fonctionne).

Longue vie à Framanews !

**Comment by pyg77** [comment]
En fait, le mini plugin est déjà implémenté ! :)
1. https://framanews.org/ttrss2/ (le ttrss2 tourne sous pgsql, on va virer le /ttrss qui escargote sous mysql ce we)
2. s'identifier
3. "Actions > Configuration" (en haut à droite)
4. Plugins
5. activer "swap_jk :   Swap j and k hotkeys (for vi brethren)"

Done ;)

**Comment by ldidry** [comment]
@fabi1cazenave : en fait j'ai déjà fait des modifications (pour traduire totalement l'appli en français) donc une de plus, une de moins…
