### ISSUE TITLE
Problème avec les flux de l'ACS

### ISSUE THREAD

**Issue by ggoubert** [framasoft/ttrss#9]
Depuis 2 semaines je suis incapable d'accéder aux flux de l'ACS (American Chemical Society). Les articles apparaissent dans l'interface ttrss mais les lien amènent vers une page d'erreur (http://pubs.acs.org/action/cookieAbsent). Si j'essaie d'accéder directement aux articles depuis leur site, il n'y a pas de problème. Les autres flux fonctionnent. Les cookies sont bien activés dans mon navigateur.

Un flux pour tester (pas besoin d'identification): http://feeds.feedburner.com/acs/accacs

Désolé si ça n'est pas le bon endroit pour rapporter un bug.

Guillaume

**Comment by ldidry** [comment]
Bonjour,

Sur quelle instance êtes-vous ? Je pourrais désactiver le plugin af_unburn qui, si je ne dis pas de bêtises, suit le lien du titre de l'article et rebondit de redirection en redirection (feedburner est un proxy de flux de rss, les titre des articles de ce flux ne sont pas un lien vers l'article mais vers une page qui redirige sur une page qui redirige, etc qui redirige sur la page de l'article).

Ce plugin utilise curl qui ne prend manifestement pas les cookies et donc retombe sur la page cookieAbsent. Donc en désactivant le plugin, vous aurez un lien vers une page qui redirige sur une page qui redirige, etc qui redirige sur la page de l'article.

Amicalement,

**Comment by ggoubert** [comment]
Bonjour,

Je pense que je suis sur l'instance 1, l'adresse que je vois est :
https://framanews.org/ttrss/index.php#f=27901&c=0

merci,

Guillaume

**Comment by ldidry** [comment]
Voilà, j'ai enlevé le plugin (les utilisateurs ont toujours le choix de l'activer dans leurs préférences).

Je clos le ticket car je pense que ça suffira, mais s'il y a un problème, n'hésitez pas à le rouvrir.

Amicalement,
